#!/usr/bin/env python3
"""Remove legacy hand-maintained JSON-LD from template.html.

Structured data is generated after page rendering by structured_data.py from
content.json and work.json. Keeping schema copy in template.html would create a
second editorial source of truth, so this script removes it before every build.
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))
PATH = os.path.join(ROOT, 'template.html')
MARKER = '<!-- Structured data is generated by structured_data.py from CMS content. -->\n'
LD_RE = re.compile(
    r'<script\b[^>]*type=["\']application/ld\+json["\'][^>]*>.*?</script>\s*',
    re.I | re.S,
)


def clean(source):
    out = LD_RE.sub('', source)
    if MARKER not in out:
        if '</head>' not in out:
            raise ValueError('template.html has no </head>')
        out = out.replace('</head>', MARKER + '</head>', 1)
    return out


def main():
    with open(PATH, encoding='utf-8') as f:
        current = f.read()
    try:
        expected = clean(current)
    except ValueError as exc:
        sys.exit('template JSON-LD cleanup failed:\n  - ' + str(exc))

    if '--check' in sys.argv:
        if current != expected:
            sys.exit('template JSON-LD cleanup check failed: legacy JSON-LD remains in template.html')
        print('template JSON-LD cleanup --check OK')
        return

    if current == expected:
        print('template JSON-LD already clean')
        return

    with open(PATH, 'w', encoding='utf-8') as f:
        f.write(expected)
    print('removed legacy template JSON-LD; CMS-derived schema is now the only source')


if __name__ == '__main__':
    main()
